### ISSUE TITLE
Error: ENOENT for bootstrap-theme.css

### ISSUE THREAD

**Issue by mallkuma** [vincentmorneau/basic-gulpfile#1]
Hi Vincent,

Not sure if I am missing something but when I start gulp I get the below error in my CLI.

> gulp
> [11:47:44] Using gulpfile ~\Dropbox\Public\basic-gulpfile\gulpfile.js
> [11:47:44] Starting 'default'...
> [11:47:44] Starting 'clean'...
> [11:47:44] Finished 'clean' after 3.66 ms
> [11:47:44] Starting 'js'...
> [11:47:45] Starting 'css'...
> [11:47:45] Starting 'img'...
> [11:47:45] Starting 'lib'...
> [11:47:45] Starting 'watch'...
> [11:47:45] Finished 'watch' after 29 ms
> [11:47:45] Finished 'default' after 819 ms
> [11:47:45] app.css 610 B
> [11:47:45] app.js 416 B
> [11:47:45] Finished 'img' after 181 ms
> **[11:47:45] 'lib' errored after 184 ms
> [11:47:45] Error: ENOENT: no such file or directory, stat 'C:\Dropbox\Public\basic-gulpfile\dist\lib\bootstrap-3.3.2-dist\css\bootstrap-theme.css'
>     at Error (native)**
> Successfully built.
> [11:47:45] app.min.css 391 B
> [11:47:45] app.min.js 229 B
> [11:47:45] Finished 'css' after 690 ms
> [11:47:45] Finished 'js' after 1.05 s

**Comment by vincentmorneau** [comment]
Hi @mallkuma,

Glad you asked. Please have a look at the new repository for this project: https://github.com/OraOpenSource/apex-frontend-boost

It's unofficial for now, but it'll launch soon. APEX Front-End Boost will be much more robust and powerful than basic-gulpfile.

Let me know if you need any help.

**Comment by mallkuma** [comment]
Hi Vincent.

I cloned the "**APEX Front-End Boost**" repo and gave it a run. It's awesome! Thanks for putting this together for the APEX community.

I really like the fact that I don't have to use Dropbox and the changes to my web files can be tested instantaneously. Earlier with "basic-gulpfile," I had to wait until Dropbox had completed syncing and then refresh the browser manually.

mallkuma

**Comment by vincentmorneau** [comment]
I really appreciate your feedback. If you encounter any issue with APEX Front-End Boost, please continue to log them over there.

It is indeed much more faster than the Dropbox method. I think people from the APEX community will pick it up.
